# Generated by Django 5.2.5 on 2025-12-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/not-found-icon-4.jpg', upload_to='profile_images'),
        ),
    ]
