# Generated by Django 5.2.5 on 2025-12-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='not-found-icon-4.jpg', upload_to='profile_images'),
        ),
    ]
