# Generated by Django 5.2.5 on 2025-09-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='ParticipantModel',
        ),
    ]
