# Generated by Django 5.2.5 on 2025-08-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='assigned_to',
            field=models.ManyToManyField(related_name='eventP', to='events.participantmodel'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventC', to='events.categorymodel'),
        ),
        migrations.AlterField(
            model_name='participantmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
