# Generated by Django 5.2.5 on 2025-09-09 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventmodel_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='Participant',
            field=models.ManyToManyField(related_name='eventP', to=settings.AUTH_USER_MODEL),
        ),
    ]
