# Generated by Django 5.2.5 on 2025-08-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventmodel_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
