# Generated by Django 5.2.5 on 2025-09-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventmodel_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='Casset',
            field=models.ImageField(blank=True, default='not-found-icon-4.jpg', null=True, upload_to='categorys_asset/'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='Easset',
            field=models.ImageField(blank=True, default='not-found-icon-4.jpg', null=True, upload_to='events_asset/'),
        ),
    ]
