# Generated by Django 5.2.5 on 2025-09-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_categorymodel_casset_eventmodel_easset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='Casset',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='Easset',
        ),
    ]
